In [ ]:
import numpy as np
import pandas as pd
import seaborn as sns

In [ ]:
df = pd.read_csv("/content/Placement_Data_Full_Class.csv")

In [ ]:
df

,sl_no,gender,ssc_p,ssc_b,hsc_p,hsc_b,hsc_s,degree_p,degree_t,workex,etest_p,specialisation,mba_p,status,salary
0,1,M,67.00,Others,91.00,Others,Commerce,58.00,Sci&Tech,No,55.0,Mkt&HR,58.80,Placed,270000.0
1,2,M,79.33,Central,78.33,Others,Science,77.48,Sci&Tech,Yes,86.5,Mkt&Fin,66.28,Placed,200000.0
2,3,M,65.00,Central,68.00,Central,Arts,64.00,Comm&Mgmt,No,75.0,Mkt&Fin,57.80,Placed,250000.0
3,4,M,56.00,Central,52.00,Central,Science,52.00,Sci&Tech,No,66.0,Mkt&HR,59.43,Not Placed,NaN
4,5,M,85.80,Central,73.60,Central,Commerce,73.30,Comm&Mgmt,No,96.8,Mkt&Fin,55.50,Placed,425000.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
210,211,M,80.60,Others,82.00,Others,Commerce,77.60,Comm&Mgmt,No,91.0,Mkt&Fin,74.49,Placed,400000.0
211,212,M,58.00,Others,60.00,Others,Science,72.00,Sci&Tech,No,74.0,Mkt&Fin,53.62,Placed,275000.0
212,213,M,67.00,Others,67.00,Others,Commerce,73.00,Comm&Mgmt,Yes,59.0,Mkt&Fin,69.72,Placed,295000.0
213,214,F,74.00,Others,66.00,Others,Commerce,58.00,Comm&Mgmt,No,70.0,Mkt&HR,60.23,Placed,204000.0
214,215,M,62.00,Central,58.00,Others,Science,53.00,Comm&Mgmt,No,89.0,Mkt&HR,60.22,Not Placed,NaN

In [ ]:
df.head(5)

,sl_no,gender,ssc_p,ssc_b,hsc_p,hsc_b,hsc_s,degree_p,degree_t,workex,etest_p,specialisation,mba_p,status,salary
0,1,M,67.00,Others,91.00,Others,Commerce,58.00,Sci&Tech,No,55.0,Mkt&HR,58.80,Placed,270000.0
1,2,M,79.33,Central,78.33,Others,Science,77.48,Sci&Tech,Yes,86.5,Mkt&Fin,66.28,Placed,200000.0
2,3,M,65.00,Central,68.00,Central,Arts,64.00,Comm&Mgmt,No,75.0,Mkt&Fin,57.80,Placed,250000.0
3,4,M,56.00,Central,52.00,Central,Science,52.00,Sci&Tech,No,66.0,Mkt&HR,59.43,Not Placed,NaN
4,5,M,85.80,Central,73.60,Central,Commerce,73.30,Comm&Mgmt,No,96.8,Mkt&Fin,55.50,Placed,425000.0

In [ ]:
df.tail(5)

,sl_no,gender,ssc_p,ssc_b,hsc_p,hsc_b,hsc_s,degree_p,degree_t,workex,etest_p,specialisation,mba_p,status,salary
210,211,M,80.6,Others,82.0,Others,Commerce,77.6,Comm&Mgmt,No,91.0,Mkt&Fin,74.49,Placed,400000.0
211,212,M,58.0,Others,60.0,Others,Science,72.0,Sci&Tech,No,74.0,Mkt&Fin,53.62,Placed,275000.0
212,213,M,67.0,Others,67.0,Others,Commerce,73.0,Comm&Mgmt,Yes,59.0,Mkt&Fin,69.72,Placed,295000.0
213,214,F,74.0,Others,66.0,Others,Commerce,58.0,Comm&Mgmt,No,70.0,Mkt&HR,60.23,Placed,204000.0
214,215,M,62.0,Central,58.0,Others,Science,53.0,Comm&Mgmt,No,89.0,Mkt&HR,60.22,Not Placed,NaN

In [ ]:

df.shape

(215, 15)

In [ ]:
print("Number of Rows",df.shape[0])
print("Number of Columns",df.shape[1])

Number of Rows 215
Number of Columns 15

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 215 entries, 0 to 214
Data columns (total 15 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   sl_no           215 non-null    int64
 1   gender          215 non-null    object
 2   ssc_p           215 non-null    float64
 3   ssc_b           215 non-null    object
 4   hsc_p           215 non-null    float64
 5   hsc_b           215 non-null    object
 6   hsc_s           215 non-null    object
 7   degree_p        215 non-null    float64
 8   degree_t        215 non-null    object
 9   workex          215 non-null    object
 10  etest_p         215 non-null    float64
 11  specialisation  215 non-null    object
 12  mba_p           215 non-null    float64
 13  status          215 non-null    object
 14  salary          148 non-null    float64
dtypes: float64(6), int64(1), object(8)
memory usage: 25.3+ KB

In [ ]:
df.isnull().sum()

sl_no              0
gender             0
ssc_p              0
ssc_b              0
hsc_p              0
hsc_b              0
hsc_s              0
degree_p           0
degree_t           0
workex             0
etest_p            0
specialisation     0
mba_p              0
status             0
salary            67
dtype: int64

In [ ]:
df["salary"] = df["salary"].fillna(int(df["salary"].median()))

In [ ]:
df.isnull().sum()

sl_no             0
gender            0
ssc_p             0
ssc_b             0
hsc_p             0
hsc_b             0
hsc_s             0
degree_p          0
degree_t          0
workex            0
etest_p           0
specialisation    0
mba_p             0
status            0
salary            0
dtype: int64

In [ ]:
df.describe()

,sl_no,ssc_p,hsc_p,degree_p,etest_p,mba_p,salary
count,215.000000,215.000000,215.000000,215.000000,215.000000,215.000000,215.000000
mean,108.000000,67.303395,66.333163,66.370186,72.100558,62.278186,281283.720930
std,62.209324,10.827205,10.897509,7.358743,13.275956,5.833385,78232.510303
min,1.000000,40.890000,37.000000,50.000000,50.000000,51.210000,200000.000000
25%,54.500000,60.600000,60.900000,61.000000,60.000000,57.945000,250000.000000
50%,108.000000,67.000000,65.000000,66.000000,71.000000,62.000000,265000.000000
75%,161.500000,75.700000,73.000000,72.000000,83.500000,66.255000,282500.000000
max,215.000000,89.400000,97.700000,91.000000,98.000000,77.890000,940000.000000

In [ ]:
df.columns

Index(['sl_no', 'gender', 'ssc_p', 'ssc_b', 'hsc_p', 'hsc_b', 'hsc_s',
       'degree_p', 'degree_t', 'workex', 'etest_p', 'specialisation', 'mba_p',
       'status', 'salary'],
      dtype='object')

In [ ]:
df['status'].unique()

array(['Placed', 'Not Placed'], dtype=object)

In [ ]:
df['status'].value_counts()

status
Placed        148
Not Placed     67
Name: count, dtype: int64

In [ ]:
df['gender'].unique()

array(['M', 'F'], dtype=object)

In [ ]:
df['gender'].value_counts()

gender
M    139
F     76
Name: count, dtype: int64

In [ ]:
df['workex'].unique()

array(['No', 'Yes'], dtype=object)

In [ ]:
df['workex'].value_counts()

workex
No     141
Yes     74
Name: count, dtype: int64

In [ ]:
df[(df['degree_t']=="Sci&Tech") & (df['status']=="Placed")].sort_values(by="salary",ascending=False).head(5)

KeyError: 'salary'

In [ ]:
df.drop(columns=['sl_no','salary'],inplace=True)

KeyError: "['sl_no', 'salary'] not found in axis"

In [ ]:
df

,gender,ssc_p,ssc_b,hsc_p,hsc_b,hsc_s,degree_p,degree_t,workex,etest_p,specialisation,mba_p,status
0,M,67.00,Others,91.00,Others,Commerce,58.00,Sci&Tech,No,55.0,Mkt&HR,58.80,Placed
1,M,79.33,Central,78.33,Others,Science,77.48,Sci&Tech,Yes,86.5,Mkt&Fin,66.28,Placed
2,M,65.00,Central,68.00,Central,Arts,64.00,Comm&Mgmt,No,75.0,Mkt&Fin,57.80,Placed
3,M,56.00,Central,52.00,Central,Science,52.00,Sci&Tech,No,66.0,Mkt&HR,59.43,Not Placed
4,M,85.80,Central,73.60,Central,Commerce,73.30,Comm&Mgmt,No,96.8,Mkt&Fin,55.50,Placed
...,...,...,...,...,...,...,...,...,...,...,...,...,...
210,M,80.60,Others,82.00,Others,Commerce,77.60,Comm&Mgmt,No,91.0,Mkt&Fin,74.49,Placed
211,M,58.00,Others,60.00,Others,Science,72.00,Sci&Tech,No,74.0,Mkt&Fin,53.62,Placed
212,M,67.00,Others,67.00,Others,Commerce,73.00,Comm&Mgmt,Yes,59.0,Mkt&Fin,69.72,Placed
213,F,74.00,Others,66.00,Others,Commerce,58.00,Comm&Mgmt,No,70.0,Mkt&HR,60.23,Placed
214,M,62.00,Central,58.00,Others,Science,53.00,Comm&Mgmt,No,89.0,Mkt&HR,60.22,Not Placed

In [ ]:
 df['ssc_b'].unique()

array(['Others', 'Central'], dtype=object)

In [ ]:
# Impute missing values with the mode after mapping
df['gender'] = df['gender'].fillna(df['gender'].mode()[0])
df['ssc_b'] = df['ssc_b'].fillna(df['ssc_b'].mode()[0])
df['hsc_s'] = df['hsc_s'].fillna(df['hsc_s'].mode()[0])

In [ ]:
df.isnull().sum()

gender            0
ssc_p             0
ssc_b             0
hsc_p             0
hsc_b             0
hsc_s             0
degree_p          0
degree_t          0
workex            0
etest_p           0
specialisation    0
mba_p             0
status            0
dtype: int64

In [ ]:
df['hsc_b'] = df['hsc_b'].map({"Central": 1, "Others": 0})

In [ ]:
df['hsc_s'] = df['hsc_s'].map({"Science": 2, "Commerce": 1, "Arts": 0})

In [ ]:
df['degree_t'] = df['degree_t'].map({"Sci&Tech": 2, "Comm&Mgmt": 1, "Others": 0})

In [ ]:
df['specialisation'] = df['specialisation'].map({"Mkt&HR": 1, "Mkt&Fin": 0})

In [ ]:
df['workex'] = df['workex'].map({"Yes": 1, "No": 0})

In [ ]:
df['status'] = df['status'].map({"Placed": 1, "Not Placed": 0})

In [ ]:
df['gender'] = df['gender'].map({"M": 1, "F": 0})

In [ ]:
df.head(2)

,gender,ssc_p,ssc_b,hsc_p,hsc_b,hsc_s,degree_p,degree_t,workex,etest_p,specialisation,mba_p,status
0,1,67.00,Others,91.00,0,1,58.00,2,0,55.0,1,58.80,1
1,1,79.33,Central,78.33,0,2,77.48,2,1,86.5,0,66.28,1

In [ ]:
X = df.drop(columns=['status'])
y = df['status']

In [ ]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=2)

#LogisticRegression

In [ ]:
import pandas as pd

X_train_encoded = pd.get_dummies(X_train, drop_first=True)
X_test_encoded = pd.get_dummies(X_test, drop_first=True)

# Make sure columns align between train and test
X_test_encoded = X_test_encoded.reindex(columns=X_train_encoded.columns, fill_value=0)

from sklearn.linear_model import LogisticRegression

log = LogisticRegression(max_iter=1000)
log.fit(X_train_encoded, y_train)

LogisticRegression(max_iter=1000)

In [ ]:
y_pred = log.predict(X_test_encoded)

In [ ]:
y_pred

array([1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1,
       1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0])

In [ ]:
from sklearn.metrics import accuracy_score, confusion_matrix, precision_score, recall_score, f1_score
accuracy_score(y_test, y_pred)

0.8372093023255814

#RandomForestClassifier

In [ ]:
from  sklearn.ensemble import RandomForestClassifier
import pandas as pd

# Apply one-hot encoding to X_train and X_test for the RandomForestClassifier
X_train_encoded_rf = pd.get_dummies(X_train, drop_first=True)
X_test_encoded_rf = pd.get_dummies(X_test, drop_first=True)

# Make sure columns align between train and test
X_test_encoded_rf = X_test_encoded_rf.reindex(columns=X_train_encoded_rf.columns, fill_value=0)


rcf = RandomForestClassifier()
rcf.fit(X_train_encoded_rf, y_train)

RandomForestClassifier()

In [ ]:
y_pred = log.predict(X_test_encoded)

In [ ]:
from sklearn.metrics import accuracy_score, confusion_matrix, precision_score, recall_score, f1_score
accuracy_score(y_test, y_pred)

0.8372093023255814

#XGBClassifier

In [ ]:
from xgboost import XGBClassifier
import pandas as pd

# Apply one-hot encoding to X_train and X_test for the RandomForestClassifier
X_train_encoded_rf = pd.get_dummies(X_train, drop_first=True)
X_test_encoded_rf = pd.get_dummies(X_test, drop_first=True)

# Make sure columns align between train and test
X_test_encoded_rf = X_test_encoded_rf.reindex(columns=X_train_encoded_rf.columns, fill_value=0)


xgb = XGBClassifier()
xgb.fit(X_train_encoded_rf, y_train)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric=None, feature_types=None,
              feature_weights=None, gamma=None, grow_policy=None,
              importance_type=None, interaction_constraints=None,
              learning_rate=None, max_bin=None, max_cat_threshold=None,
              max_cat_to_onehot=None, max_delta_step=None, max_depth=None,
              max_leaves=None, min_child_weight=None, missing=nan,
              monotone_constraints=None, multi_strategy=None, n_estimators=None,
              n_jobs=None, num_parallel_tree=None, ...)

In [ ]:
from sklearn.metrics import accuracy_score, confusion_matrix, precision_score, recall_score, f1_score
accuracy_score(y_test, y_pred)

0.8372093023255814

In [ ]:
confusion_matrix(y_test, y_pred)

array([[ 8,  5],
       [ 2, 28]])

In [ ]:
%%capture
pip instal gradio

In [ ]:
# placement_predictor_gradio_debug.py
"""
Robust Gradio app for Placement_Data_Full_Class.csv
- Handles common problems: missing file, messy categorical strings, NaNs, missing xgboost, label encoding mismatches
- Returns prediction AND debug logs so you can see what went wrong
"""

import os
import traceback
import pandas as pd
import gradio as gr
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score

# Try import xgboost but degrade gracefully if missing
try:
    from xgboost import XGBClassifier
    XGB_AVAILABLE = True
except Exception as e:
    XGB_AVAILABLE = False

DATA_PATH = "Placement_Data_Full_Class.csv"

def load_and_prepare(path):
    logs = []
    if not os.path.exists(path):
        raise FileNotFoundError(f"Dataset not found at '{path}'. Put the CSV in the same folder or change DATA_PATH.")
    df = pd.read_csv(path)
    logs.append(f"Loaded dataset with shape {df.shape}")

    # Drop obviously leaking or unneeded cols if present
    for c in ['sl_no', 'salary']:
        if c in df.columns:
            df = df.drop(columns=[c])
            logs.append(f"Dropped column '{c}'")

    if 'status' not in df.columns:
        raise ValueError(f"Target column 'status' not found. Columns: {list(df.columns)}")

    # Clean up object columns: strip whitespace and unify strings
    for col in df.select_dtypes(include=['object']).columns:
        df[col] = df[col].astype(str).str.strip()
        # replace empty strings with a sentinel
        df[col] = df[col].replace({'': 'missing', 'nan': 'missing', 'None': 'missing'})
    logs.append("Stripped and cleaned object columns; filled obvious empties with 'missing'")

    # Try simple mapping for common 'status' values (many datasets use 'Placed' / 'Not Placed')
    status_processed = df['status'].astype(str).str.lower().str.replace(r'[_\s]+',' ', regex=True).str.strip()
    unique_status = sorted(status_processed.unique())
    logs.append(f"Unique target (lowercased): {unique_status}")

    # Map common variants to 0/1 if possible
    mapping = {}
    if set(unique_status).issubset({'placed','not placed','notplaced','placed'}):
        mapping = {s: (1 if 'place' in s else 0) for s in unique_status}
        df['status'] = status_processed.map(mapping)
        logs.append(f"Applied direct mapping for status: {mapping}")
    else:
        # fallback to label encoder
        le_status = LabelEncoder()
        df['status'] = le_status.fit_transform(df['status'].astype(str))
        logs.append(f"Used LabelEncoder for status; classes: {le_status.classes_.tolist()}")

    # Now encode categorical features with LabelEncoder and keep encoders
    label_encoders = {}
    for col in df.select_dtypes(include=['object']).columns:
        if col == 'status':
            continue
        le = LabelEncoder()
        df[col] = df[col].astype(str)  # ensure strings
        df[col] = df[col].fillna('missing')
        try:
            df[col] = le.fit_transform(df[col])
            label_encoders[col] = le
            logs.append(f"Label-encoded column '{col}'; classes: {le.classes_.tolist()[:10]}{'...' if len(le.classes_)>10 else ''}")
        except Exception as e:
            # If for some reason encoding fails, convert to numeric where possible
            logs.append(f"Warning: Label encoding failed for {col} — {e}; attempting numeric coercion")
            df[col] = pd.to_numeric(df[col], errors='coerce').fillna(0).astype(float)

    # Handle missing numeric values
    numeric_cols = df.select_dtypes(include=['number']).columns.tolist()
    if df[numeric_cols].isnull().any().any():
        df[numeric_cols] = df[numeric_cols].fillna(df[numeric_cols].median())
        logs.append("Filled numeric NaNs with medians")

    # Prepare X,y
    X = df.drop(columns=['status'])
    y = df['status'].astype(int)

    # Create scaler and scale
    scaler = StandardScaler()
    X_scaled = scaler.fit_transform(X)

    logs.append("Preprocessing complete.")
    return X, y, label_encoders, scaler, logs

# Wrap dataset prep + model training so we can show useful errors
def build_models():
    try:
        X, y, label_encoders, scaler, logs = load_and_prepare(DATA_PATH)
    except Exception as e:
        raise RuntimeError("Failed to load/preprocess dataset:\n" + traceback.format_exc())

    # split
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
    # Train baseline models; XGBoost optional
    models = {}
    training_logs = []
    try:
        lr = LogisticRegression(max_iter=2000)
        lr.fit(scaler.transform(X_train), y_train)
        models['Logistic Regression'] = lr
        training_logs.append("Trained Logistic Regression")
    except Exception as e:
        training_logs.append("Failed Logistic Regression: " + str(e))

    try:
        rf = RandomForestClassifier(n_estimators=200, random_state=42)
        rf.fit(scaler.transform(X_train), y_train)
        models['Random Forest'] = rf
        training_logs.append("Trained Random Forest")
    except Exception as e:
        training_logs.append("Failed Random Forest: " + str(e))

    if XGB_AVAILABLE:
        try:
            xgb = XGBClassifier(use_label_encoder=False, eval_metric='logloss', random_state=42)
            xgb.fit(scaler.transform(X_train), y_train)
            models['XGBoost'] = xgb
            training_logs.append("Trained XGBoost")
        except Exception as e:
            training_logs.append("Failed XGBoost: " + str(e))
    else:
        training_logs.append("XGBoost not available in environment — skipping it")

    # compute accuracies for successful models
    accuracies = {}
    for name, m in models.items():
        try:
            preds = m.predict(scaler.transform(X_test))
            accuracies[name] = round(float(accuracy_score(y_test, preds) * 100), 2)
        except Exception as e:
            accuracies[name] = f"err: {e}"

    return {
        'X': X, 'y': y, 'label_encoders': label_encoders,
        'scaler': scaler, 'models': models, 'accuracies': accuracies,
        'logs': logs + training_logs
    }

# Build models on import (so UI is ready); if something fails we capture the exception and show it
try:
    workspace = build_models()
except Exception as e:
    workspace = None
    build_error = traceback.format_exc()

def predict_and_debug(*user_inputs, model_name):
    """
    user_inputs are in the same order as workspace['X'].columns
    Returns (prediction_text, debug_log)
    """
    debug_lines = []
    if workspace is None:
        return "❌ App build failed", f"App build exception:\n{build_error}"

    X_cols = workspace['X'].columns.tolist()
    # last element of user_inputs is model_name due to how we will wire inputs; but in this function we expect model_name separately in Gradio
    try:
        # build input dict
        if len(user_inputs) != len(X_cols):
            debug_lines.append(f"ERROR: Expected {len(X_cols)} inputs but got {len(user_inputs)}")
            return "❌ Input shape mismatch", "\n".join(debug_lines)

        input_dict = dict(zip(X_cols, user_inputs))
        debug_lines.append(f"Raw inputs: {input_dict}")

        # Convert categorical text back to encoder ints
        for col, le in workspace['label_encoders'].items():
            if col not in input_dict:
                continue
            val = input_dict[col]
            # If the user selected a numeric value (maybe someone typed index), accept it
            if isinstance(val, (int, float)) and str(val) in map(str, range(10000)):  # crude numeric pass-through
                # keep it
                input_dict[col] = val
            else:
                # try transform; LabelEncoder expects exact match of the original class strings
                try:
                    transformed = le.transform([str(val)])[0]
                    input_dict[col] = int(transformed)
                    debug_lines.append(f"Transformed '{col}':'{val}' -> {transformed}")
                except Exception as e:
                    # try lower/strip variants
                    try:
                        alt = str(val).strip()
                        transformed = le.transform([alt])[0]
                        input_dict[col] = int(transformed)
                        debug_lines.append(f"Transformed (alt) '{col}':'{alt}' -> {transformed}")
                    except Exception as e2:
                        debug_lines.append(f"Couldn't transform '{col}' value '{val}': {e2}. Trying numeric coercion.")
                        try:
                            input_dict[col] = int(float(val))
                        except Exception:
                            input_dict[col] = 0
                            debug_lines.append(f"Fallback: set '{col}' to 0")

        # Create DataFrame row in same column order
        row = pd.DataFrame([input_dict], columns=X_cols)
        debug_lines.append(f"Row before scaling:\n{row.to_dict(orient='records')[0]}")

        # Scale and predict
        X_scaled = workspace['scaler'].transform(row)
        model = workspace['models'].get(model_name)
        if model is None:
            return "❌ Model not available", f"Requested model '{model_name}' not found. Available: {list(workspace['models'].keys())}"
        pred = model.predict(X_scaled)[0]
        label_text = "🎓 Placed" if int(pred) == 1 else "❌ Not Placed"
        debug_lines.append(f"Model '{model_name}' predicted: {pred}")
        debug_lines.append(f"Model accuracies: {workspace['accuracies']}")
        return label_text, "\n".join(debug_lines)
    except Exception:
        debug_lines.append("EXCEPTION:\n" + traceback.format_exc())
        return "❌ Error during prediction", "\n".join(debug_lines)

# If workspace built, prepare Gradio inputs/choices
if workspace is None:
    # minimal placeholder UI that just shows error
    def dummy(_=None):
        return "App build failed", build_error
    demo = gr.Interface(fn=dummy,
                        inputs=[],
                        outputs=[gr.Textbox(label="Prediction"), gr.Textbox(label="Debug")],
                        title="Placement Predictor - BUILD ERROR",
                        description="The app failed to build. Check debug output.")
else:
    X_cols = workspace['X'].columns.tolist()
    gr_inputs = []
    for col in X_cols:
        if col in workspace['label_encoders']:
            choices = [str(c) for c in workspace['label_encoders'][col].classes_.tolist()]
            gr_inputs.append(gr.Dropdown(choices=choices, label=col))
        else:
            # numeric
            gr_inputs.append(gr.Number(label=col))

    model_choices = list(workspace['models'].keys())
    gr_inputs.append(gr.Dropdown(choices=model_choices, label="Select Model", value=model_choices[0]))

    demo = gr.Interface(
        fn=predict_and_debug,
        inputs=gr_inputs,
        outputs=[gr.Textbox(label="Placement Prediction"), gr.Textbox(label="Debug / Trace")],
        title="🎓 Placement Prediction (Debug mode)",
        description="Make selections for categorical fields (they're shown as text) and numbers for numeric fields. Debug output shows internal steps.",
        allow_flagging="never"
    )

# Launch: inline=True works in notebooks; in local it will open the browser.
if __name__ == "__main__":
    # inline=True works inside notebooks; change to inline=False if you prefer separate browser tab
    demo.launch(inline=True, share=False)

/usr/local/lib/python3.12/dist-packages/gradio/interface.py:415: UserWarning: The `allow_flagging` parameter in `Interface` is deprecated. Use `flagging_mode` instead.
  warnings.warn(

Colab notebook detected. To show errors in colab notebook, set debug=True in launch()
Note: opening Chrome Inspector may crash demo inside Colab notebooks.
* To create a public link, set `share=True` in `launch()`.

In [ ]:
df

,sl_no,gender,ssc_p,ssc_b,hsc_p,hsc_b,hsc_s,degree_p,degree_t,workex,etest_p,specialisation,mba_p,status,salary
0,1,M,67.00,Others,91.00,Others,Commerce,58.00,Sci&Tech,No,55.0,Mkt&HR,58.80,Placed,270000.0
1,2,M,79.33,Central,78.33,Others,Science,77.48,Sci&Tech,Yes,86.5,Mkt&Fin,66.28,Placed,200000.0
2,3,M,65.00,Central,68.00,Central,Arts,64.00,Comm&Mgmt,No,75.0,Mkt&Fin,57.80,Placed,250000.0
3,4,M,56.00,Central,52.00,Central,Science,52.00,Sci&Tech,No,66.0,Mkt&HR,59.43,Not Placed,NaN
4,5,M,85.80,Central,73.60,Central,Commerce,73.30,Comm&Mgmt,No,96.8,Mkt&Fin,55.50,Placed,425000.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
210,211,M,80.60,Others,82.00,Others,Commerce,77.60,Comm&Mgmt,No,91.0,Mkt&Fin,74.49,Placed,400000.0
211,212,M,58.00,Others,60.00,Others,Science,72.00,Sci&Tech,No,74.0,Mkt&Fin,53.62,Placed,275000.0
212,213,M,67.00,Others,67.00,Others,Commerce,73.00,Comm&Mgmt,Yes,59.0,Mkt&Fin,69.72,Placed,295000.0
213,214,F,74.00,Others,66.00,Others,Commerce,58.00,Comm&Mgmt,No,70.0,Mkt&HR,60.23,Placed,204000.0
214,215,M,62.00,Central,58.00,Others,Science,53.00,Comm&Mgmt,No,89.0,Mkt&HR,60.22,Not Placed,NaN